{
    'name': 'Material Request',
    'version': '18.0',
    'summary': 'Material Request for MRP',
    'sequence': 10,
    'description': """ Material Request For MRP """,
    'depends': ['base', 'mrp', 'stock', 'purchase_requisition'],
    'data': [
        'views/mrp_full_view.xml',
        'security/ir.model.access.csv',
        'data/seqence.xml',
        'data/groups.xml',
        'views/mrp_extended.xml',
        'views/material_request.xml',
        'views/user_material_request.xml',
        'wizard/purchae_request.xml',
        'wizard/backorder.xml',
        # 'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
