{
    'name': "Website Helpdesk Management",
    'version': '18.0.1.0.3',
    'category': 'Website',
    'summary': "Create and manage helpdesk tickets from website and backend.",
    'description': """Website Helpdesk Management for Odoo 18 with ticket creation,
                      customer portal, live voice recording, image upload, and video recording.""",
    'author': "Cybrosys Techno Solutions",
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "http://www.cybrosys.com",
    # 'depends': [
    #     'website',
    #     'project',
    #     'sale_project',
    #     'sale_management',  # ✅ add this line
    #     'hr_timesheet',
    #     'mail',
    #     'contacts',
    # ],
    #
    # 'data': [
    #     'security/odoo_website_helpdesk_groups.xml',
    #     'security/odoo_website_helpdesk_security.xml',
    #     'security/ir.model.access.csv',
    #     'data/helpdesk_category_data.xml',
    #     'data/helpdesk_replay_template_data.xml',
    #     'data/helpdesk_type_data.xml',
    #     'data/groups.xml',
    #     'data/ir_cron_data.xml',
    #     'data/ir_sequence_data.xml',
    #     'data/mail_template_data.xml',
    #     'data/ticket_stage_data.xml',
    #     'views/helpdesk_category_views.xml',
    #     'views/helpdesk_tag_views.xml',
    #     'views/helpdesk_type_views.xml',
    #     'views/merge_ticket_views.xml',
    #     'views/odoo_website_helpdesk_portal_templates.xml',
    #     'views/portal_templates.xml',
    #     'views/rating_form.xml',
    #     'report/helpdesk_ticket_report_template.xml',
    #     'views/res_config_settings_views.xml',
    #     'views/team_helpdesk_views.xml',
    #     'views/ticket_helpdesk_views.xml',
    #     'views/ticket_stage_views.xml',
    #     'views/website_form.xml',
    #     'views/helpdesk_menu_views.xml',
    # ],
    #
    # # ✅ Combine all frontend & backend assets here
    # 'assets': {
    #     'web.assets_frontend': [
    #         '/odoo_website_helpdesk/static/src/js/ticket_details.js',
    #         '/odoo_website_helpdesk/static/src/js/portal_search.js',
    #         '/odoo_website_helpdesk/static/src/js/multiple_product_choose.js',
    #         # 'odoo_website_helpdesk/static/src/xml/helpdesk_attachment_manager.xml',
    #
    #     ],
    #     'web.assets_backend': [
    #         'odoo_website_helpdesk/static/src/js/audio_recorder.js',
    #         'odoo_website_helpdesk/static/src/xml/audio_recorder_template.xml',
    #         'odoo_website_helpdesk/static/src/css/audio_recorder.css',
    #     ],
    # },

    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
